vulnerabilities:
  - id: CVE-2025-12816
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2025-66031
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2025-15284
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
