vulnerabilities:
  - id: CVE-2025-12816
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2025-66031
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-27601
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-32141
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33228
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33937
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33938
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33939
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33940
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33941
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33891
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33894
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33895
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33896
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
  - id: CVE-2026-33671
    statement: Waiting for an updated newman version > `6.2.2` - https://github.com/postmanlabs/newman/tags
    expired_at: 2026-06-01
