{{- if not .Values.postman.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postman.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  apiKey: {{ .Values.postman.apiKey | b64enc | quote }}
{{- end }}
